# GitHub Sponsorship Configuration (.github/FUNDING.yml)
# Documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - 'https://github.com/zuikre/okvir#support--sponsorship'
  - 'https://tronscan.org/#/address/TPT7y8iGjArHS7PtwpgT7F13umzxFriUWB'

